language: node_js
dist: xenial

sudo: false
env:
  global:
    - REGION=us-east-1
    - BUCKET=betaflight.com

addons:
  apt:
    update: true
    packages:
      - awscli

before_script:

script:
  - bash "${TRAVIS_BUILD_DIR}/scripts/build.sh"

deploy:
  provider: script
  script: bash "${TRAVIS_BUILD_DIR}/scripts/build.sh deploy"
  skip_cleanup: true
  on:
    branch: release

