language: node_js
dist: trusty

sudo: false
env:
  global:
    - REGION=us-east-1
    - BUCKET=betaflight.com

addons:
  apt:
    update: true
    packages:
      - awscli

before_script:

script:
  - hugo -s "${TRAVIS_BUILD_DIR}" -d "${TRAVIS_BUILD_DIR}/public"

deploy:
  provider: script
  script: bash "${TRAVIS_BUILD_DIR}/scripts/deploy.sh"
  skip_cleanup: true
  on:
    branch: master

