name: CI - Build only

on: 
  push:
    branches:
    - actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - if: github.ref == 'refs/heads/actions' 
      name: Run the build script
      run: ./scripts/build.sh
